apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: numericapp
  name: numericapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: numericapp
  strategy: {}
  template:
    metadata:
      labels:
        app: numericapp
    spec:
      containers:
      - image: replace
        name: numericapp-container
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: numericapp
  name: numericapp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: numericapp
  type: NodePort
