apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-app
  name: hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloapp
  strategy: {}
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        name: helloapp-container
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloapp
  name: helloapp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  selector:
    app: helloapp
  type: NodePort
